[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# 添加下面两行：开启优化器和 IR 编译
optimizer = true
via_ir = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
